
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zmhsb/config
          username: 1041160678@qq.com
          password: abc520123!
server:
  port: 9100

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8082/eureka/

